import Provider from "./Components/Provider";
import Header from "./Components/Header";
import Footer from "./Components/Footer";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  const session = getServerSession(authOptions);
  return (
    <html lang="en" className={`${inter.className} h-full scroll-smooth antialiased`}>
      <body className="flex h-full flex-col">
        <Provider session={session}>
          <Header />
          <main className="grow">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
